import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import localFont from "next/font/local";
import "./globals.css";

import { JotaiProvider } from "@/providers/jotai-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { ScrollProvider } from "@/providers/scroll-provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { NextAuthProvider } from "@/providers/next-auth-provider";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { ToastProvider } from "@/providers/toast-provider";

/* ------------------------------------------------------------------ */
/*                            LOCAL FONTS                             */
/* ------------------------------------------------------------------ */

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "FileBed",
  description: "Generated by create next app",
};

/* ------------------------------------------------------------------ */
/*                             LAYOUT                                 */
/* ------------------------------------------------------------------ */
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  /* ▶︎▶︎ server-side session fetch  */
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          {/* pass the pre-fetched session ↓ */}
          <NextAuthProvider session={session}>
            <JotaiProvider>
              <ThemeProvider>
                <ScrollProvider>
                  <Header />
                  {children}
                  <Footer />
                </ScrollProvider>
              </ThemeProvider>
            </JotaiProvider>
          </NextAuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
