version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:  mikanirobytes
      MYSQL_DATABASE:       mikanirobytes
      MYSQL_USER:           mikanirobytes
      MYSQL_PASSWORD:       mikanirobytes
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD","sh","-c","mysqladmin ping -h 127.0.0.1 -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} --silent"]
      interval: 10s
      retries: 5
    expose: ["3306"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_ENGINE:   mysql
      DB_HOST:     mysql
      DB_PORT:     3306
      DB_NAME:     mikanirobytes
      DB_USER:     mikanirobytes
      DB_PASSWORD: mikanirobytes
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - uploads:/app/uploads
    expose: ["8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NODE_ENV: production
    restart: unless-stopped
    expose: ["3000"]
    depends_on: ["backend"]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - uploads:/uploads:ro
    ports:
      - "12171:80"
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
  uploads: